config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path_prefix: 'my', controllers: { :sessions => "users/sessions",registrations: "users/registrations" }
  resources :users
  root to: 'pages#index'
  resources :zombiedata
  resources :zombies
  get '/search'=> 'zombiedata#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount Api, at: 'api/'
end

app/controllers/zombiedata_controller.rb
class ZombiedataController < ApplicationController
  include ApiCommunication
  protect_from_forgery with: :null_session
  before_action :set_zombiedatum, only: [:show, :edit, :update, :destroy]

  # GET /zombiedata
  # GET /zombiedata.json
  def index
    @zombiedata = Zombiedatum.all
  end

  # GET /zombiedata/1
  # GET /zombiedata/1.json
  def show
  end

  # GET /zombiedata/new
  def new
    @zombiedatum = Zombiedatum.new
  end

  # GET /zombiedata/1/edit
  def edit
  end

  # POST /zombiedata
  # POST /zombiedata.json
  def create
    @zombiedatum = Zombiedatum.new(zombiedatum_params)
    respond_to do |format|
      if @zombiedatum.save
        api_record_create @zombiedatum
        format.html { redirect_to @zombiedatum, notice: 'Zombiedatum was successfully created.' }
        format.json { render :show, status: :created, location: @zombiedatum }
      else
        format.html { render :new }
        format.json { render json: @zombiedatum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zombiedata/1
  # PATCH/PUT /zombiedata/1.json
  def update
    if params[:zombiedatum][:status] == "Cured"
      @zombiedatum.destroy
      api_record_delete @zombiedatum
      redirect_to action: "index"
    else
      respond_to do |format|
        if @zombiedatum.update(zombiedatum_params)
          api_record_update @zombiedatum
          format.html { redirect_to @zombiedatum, notice: 'Zombiedatum was successfully updated.' }
          format.json { render :show, status: :ok, location: @zombiedatum }
        else
          format.html { render :edit }
          format.json { render json: @zombiedatum.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /zombiedata/1
  # DELETE /zombiedata/1.json
  def destroy
    @zombiedatum.destroy
    respond_to do |format|
      format.html { redirect_to zombiedata_url, notice: 'Zombiedatum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    #@search_result = Zombiedatum.where(['name LIKE ?',"%#{params[:q]}%"]) if !params[:q].blank?
    if params[:q].present?
      @search_result = Zombiedatum.find(params[:q]) if Zombiedatum.exists?(id:params[:q])
      @search_result = api_record_find params if @search_result.blank?
    else
      flash[:notice] = 'Record not found.' if @search_result.nil?
      redirect_to action: "index"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zombiedatum
      @zombiedatum = Zombiedatum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zombiedatum_params
      params.require(:zombiedatum).permit(:name, :age, :weight, :status)
    end

end

app/helpers/zombiedata_helper.rb
module ZombiedataHelper
end

app/views/zombiedata/_form.html.erb
<%= form_for(zombiedatum) do |f| %>
    <% if zombiedatum.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(zombiedatum.errors.count, "error") %> prohibited this zombie from being saved:</h2>
          <ul>
            <% zombiedatum.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :age %>
      <%= f.number_field :age %>
    </div>

    <div class="field">
      <%= f.label :weight %>
      <%= f.number_field :weight %>
    </div>
    <% if params[:action]=="edit" %>
      <div class="field">
        <%= f.label :status %>
        <%= text_field :zombiedatum,:status, disabled: true %>
      </div>
    <%end %>

    <div class="field">
      <%= f.label :status,"Status change to: " %>
      <%= f.select(:status,params[:action]=="new"?['Inactive']:Zombiedatum::STATUS, {:include_blank => false} ) %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>

<% end %>

app/views/zombiedata/edit.html.erb
<h1>Editing Zombiedatum</h1>

<%= render 'form', zombiedatum: @zombiedatum %>

<%= link_to 'Show', @zombiedatum %> |
<%= link_to 'Back', zombiedata_path %>

app/views/zombiedata/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Zombiedata</h1>

<table>
  <thead>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Age</th>
    <th>Weight</th>
    <th>Status</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
    <% @zombiedata.each do |zombiedatum| %>
      <tr>
        <td><%= zombiedatum.id %></td>
        <td><%= zombiedatum.name %></td>
        <td><%= zombiedatum.age %></td>
        <td><%= zombiedatum.weight %></td>
        <td><%= zombiedatum.status %></td>
        <td><%= link_to 'Show', zombiedatum %></td>
        <td><%= link_to 'Edit', edit_zombiedatum_path(zombiedatum) %></td>
        <td><%= link_to 'Destroy', zombiedatum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div>
  <%= form_tag("search", method: "get") do %>
      <%= label_tag(:q, "Search by ID:") %>
      <%= text_field_tag(:q) %>
      <%= submit_tag("Search") %>
  <% end %>
</div>


<% if !@search_result.blank? %>

  <h3>Data Found </h3>

  <table>
    <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Age</th>
      <th>Weight</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
      <tr>
        <td><%= @search_result.id %></td>
        <td><%= @search_result.name %></td>
        <td><%= @search_result.age %></td>
        <td><%= @search_result.weight %></td>
        <td><%= @search_result.status %></td>
        <td><%= link_to 'Show', @search_result %></td>
        <td><%= link_to 'Edit', edit_zombiedatum_path(@search_result) %></td>
        <td><%= link_to 'Destroy', @search_result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    </tbody>
  </table>

<% end %>

<br>

<%= link_to 'New Zombiedatum', new_zombiedatum_path %>

app/views/zombiedata/new.html.erb
<h1>New Zombiedatum</h1>

<%= render 'form', zombiedatum: @zombiedatum %>

<%= link_to 'Back', zombiedata_path %>

app/views/zombiedata/search.erb
<p id="notice"><%= notice %></p>

<h1>Zombiedata</h1>

<div>
  <%= form_tag("search", method: "get") do %>
      <%= label_tag(:q, "Search by ID :") %>
      <%= text_field_tag(:q) %>
      <%= submit_tag("Search") %>
  <% end %>
</div>


<% if !@search_result.blank? %>

  <h3>Data Found </h3>

  <table>
    <thead>
      <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Age</th>
        <th>Weight</th>
        <th>Status</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @search_result['id'] %></td>
        <td><%= @search_result['name'] %></td>
        <td><%= @search_result['age'] %></td>
        <td><%= @search_result['weight'] %></td>
        <td><%= @search_result['status'] %></td>
      </tr>
    </tbody>
  </table>
<% end %>

<br>
<%= link_to 'Back', zombiedata_path %>

<%= link_to 'New Zombiedatum', new_zombiedatum_path %>

app/views/zombiedata/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @zombiedatum.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @zombiedatum.age %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @zombiedatum.weight %>
</p>

<p>
  <strong>Status:</strong>
  <%= @zombiedatum.status %>
</p>

<%= link_to 'Edit', edit_zombiedatum_path(@zombiedatum) %> |
<%= link_to 'Back', zombiedata_path %>